apiVersion: apps/v1
kind: Deployment
metadata:
  name: vertx-create-span
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vertx-create-span
  template:
    metadata:
      labels:
        app: vertx-create-span
      annotations:
        sidecar.opentelemetry.io/inject: sidecar-jaeger
    spec:
      containers:
      - name: vertx-create-span
        image: jpkroehling/vertx-create-span:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: OTEL_SERVICE_NAME
          value: "vertx-create-span"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: vertx-create-span-service
spec:
  selector:
    app: vertx-create-span
  ports:
  - port: 80
    targetPort: 3000
