apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-python
  template:
    metadata:
      labels:
        app: app-python
      annotations:
        # Note: Use true or name the instrumentation, instrumentation.opentelemetry.io/inject-python: python-instrumentation
        instrumentation.opentelemetry.io/inject-python: "true"
    spec:
      containers:
      - name: app-python
        image: ezmo/app-python:v1.0
        imagePullPolicy: IfNotPresent
        env:
        - name: OTEL_SERVICE_NAME
          value: "app-python"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: app-python-service
spec:
  selector:
    app: app-python
  ports:
  - port: 8000
    targetPort: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-python-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: python.example.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app-python-service
            port:
              number: 8000
