apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-node
  template:
    metadata:
      labels:
        app: app-node
      annotations:
        instrumentation.opentelemetry.io/inject-nodejs: node-instrumentation
    spec:
      containers:
      - name: app-node
        image: ezmo/app-node:v1.0
        imagePullPolicy: IfNotPresent
        env:
        - name: OTEL_SERVICE_NAME
          value: "app-node"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: app-node-service
spec:
  selector:
    app: app-node
  ports:
  - port: 80
    targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-node-ingress
spec:
  rules:
  - http:
      paths:
      - path: /nodes
        pathType: Prefix
        backend:
          service:
            name: app-node-service
            port:
              number: 80
