apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: platform
  namespace: observability
  labels:
    monitoring: prometheus
spec:
  image: otel/opentelemetry-collector-contrib:latest
  mode: "deployment"
  hostNetwork: true
  replicas: 1
  serviceAccount: platform-agent
  env:
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
  tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
      prometheus:
        config:
          scrape_configs:
          - job_name: otel-collector-metrics
            scrape_interval: 30s
            static_configs:
            - targets: ['${env:POD_IP}:8888']

    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15
      batch:
        send_batch_size: 10000
        timeout: 10s
    
    exporters:
      otlp:
        endpoint: tempo-grafana-distributor.observability.svc.cluster.local:4317
        tls:
         insecure: true
        sending_queue:
          num_consumers: 4
          queue_size: 100
        retry_on_failure:
          enabled: true
      # NOTE: Prior to v0.86.0 use `logging` instead of `debug`.
      debug:
    
    extensions:
      zpages: {}
      memory_ballast:
        # Memory Ballast size should be max 1/3 to 1/2 of memory.
        size_mib: 165

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [debug, otlp]
        metrics:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [debug]
        logs:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [debug]
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: platform-collector-ingress
  namespace: observability
spec:
  ingressClassName: nginx
  rules:
  - host: collector.observability.platform.local
    http:
      paths:
      - path: /v1/traces
        pathType: Prefix
        backend:
          service:
            name: platform-collector
            port:
              number: 4318
      - path: /v1/traces
        pathType: Prefix
        backend:
          service:
            name: platform-collector
            port:
              number: 4317
