apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: platform-collector
  namespace: observability
  labels:
    prometheus: main
spec:
  endpoints:
  - port: monitoring
  selector:
    matchLabels:
      monitoring: prometheus
