apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app-metric-generator
  labels:
    prometheus: main
spec:
  endpoints:
  - port: web
  selector:
    matchLabels:
      monitoring: prometheus
