apiVersion: batch/v1
kind: Job
metadata:
  name: generate-traces
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: tracegen
        image: ghcr.io/grafana/xk6-client-tracing:v0.0.2
        env:
        - name: ENDPOINT
          value: platform-agent-collector.observability.svc.cluster.local:4317
